version: '3'

services:
  book-club:
    image: node:20
    # 設定開發容器名稱
    container_name: book-club-dev
    restart: "no"
    # 指定工作目錄
    working_dir: /root/book-club
    volumes:
      # 掛載根目錄下資料夾到容器中
      - ../:/root/book-club
    # 安裝 pm2 及 持久化容器
    command: sh -c "npm i pm2 -g && tail -f /dev/null"